version: "3"
services:
  frontend:
    build: ./frontend
    environment:
      - NODE_ENV=production
      - BACKEND=http://localhost
      - BACKENDPORT=3001
      - PORT=3000
    expose:
      - 3000
    ports:
      - 3000:3000
  backend:
    build: ./backend
    environment:
      - NODE_ENV=production
      - PORT=3001
      - FRONTEND=http://localhost
      - FRONTENDPORT=3000
    expose:
      - 3001
    ports:
      - 3001:3001
